[package]
name = "kaori_hsm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kaori_hsm_derive= {path = "../kaori_hsm_derive/"}

[dev-dependencies]
rand = "0.8.5"
